using Atoms.Exceptions;
using Atoms.Repositories;
using Atoms.Repositories.Factories;
using Atoms.Utils;
using AtomsIntegrationTests.Models;

namespace AtomsIntegrationTests.RepositoriesTests.AtomicRepositoryTests
{
	public abstract class CreateManyAsyncTests : IDisposable
	{
		private readonly IAtomicRepository<BlogPostAuthor> authorRepo;
		private readonly IAtomicRepository<CustomerAddress> customerAddressRepo;
		private readonly IAtomicRepository<JobPosting> jobPostingRepo;
		private readonly IAtomicRepository<Employee> employeeRepo;
		private readonly CustomerAddress customerAddress = new CustomerAddress
		{
			PhoneNumber = "+1234567890",
			City = "Sacramento",
			Province = "California"
		};

		private readonly BlogPostAuthor author = new BlogPostAuthor
		{
			AuthorId = 2L,
			AuthorName = "Test",
			AuthorSinceDate = DateTime.Today
		};

		private readonly JobPosting jobPosting = new JobPosting
		{
			PostingId = 456L,
			EmployerId = 321L
		};

		private readonly Employee employee = new Employee
		{
			EmployeeId = Guid.NewGuid(),
			Salary = 120_000.00M
		};

		private readonly Employee employee2 = new Employee
		{
			EmployeeId = Guid.NewGuid(),
			Salary = 70_000.00M
		};

		private readonly Employee employee3 = new Employee
		{
			EmployeeId = Guid.NewGuid(),
			Salary = 95_000.00M
		};

		public CreateManyAsyncTests(
			IAtomicRepositoryFactory<BlogPostAuthor> authorRepoFactory,
			IAtomicRepositoryFactory<CustomerAddress> customerAddressRepoFactory,
			IAtomicRepositoryFactory<JobPosting> jobPostingRepoFactory,
			IAtomicRepositoryFactory<Employee> employeeRepoFactory,
			string connectionString
		)
		{
			authorRepo = authorRepoFactory.CreateRepository(connectionString);
			customerAddressRepo = customerAddressRepoFactory.CreateRepository(connectionString);
			jobPostingRepo = jobPostingRepoFactory.CreateRepository(connectionString);
			employeeRepo = employeeRepoFactory.CreateRepository(connectionString);
		}

		[Fact]
		public async Task WhenWeCreateABlogPostAuthor_ThenWhenWeGetItBackItExists()
		{
			// Act
			IEnumerable<BlogPostAuthor> createdAuthors = await authorRepo.CreateManyAsync(new List<BlogPostAuthor> { author });
			// Assert
			var retrievedAuthor = await GetExistingModelAsync(author, authorRepo);
			Assert.Equal(createdAuthors.First().AuthorId, retrievedAuthor.AuthorId);
		}


		[Fact]
		public async Task GivenACustomerAddressWithSomeNulls_WhenWeCreateOne_ThenItOnlyHasNonNullFieldsDefined()
		{
			// Act
			IEnumerable<CustomerAddress> createdCustomerAddresses = await customerAddressRepo.CreateManyAsync(new List<CustomerAddress> { customerAddress });
			// Assert
			var retrievedCustomerAddress = await GetExistingModelAsync(createdCustomerAddresses.First(), customerAddressRepo);
			Assert.Equal(customerAddress.PhoneNumber, retrievedCustomerAddress.PhoneNumber);
			Assert.Equal(customerAddress.City, retrievedCustomerAddress.City);
			Assert.Equal(customerAddress.Province, retrievedCustomerAddress.Province);
			Assert.Null(retrievedCustomerAddress.UnitNumber);
			Assert.Null(retrievedCustomerAddress.StreetNumber);
			Assert.Null(retrievedCustomerAddress.Street);
			Assert.Null(retrievedCustomerAddress.PostalCode);
			Assert.Null(retrievedCustomerAddress.Country);
		}

		[Fact]
		public async Task GivenABlogPostAuthorAlreadyExists_WhenWeAttemptToCreateTheSameOne_ThenADuplicateUniqueIdExceptionIsThrown()
		{
			// Assert
			await Assert.ThrowsAsync<DuplicateUniqueIdException>(async () =>
			{
				// Act
				await authorRepo.CreateManyAsync(new List<BlogPostAuthor> { author, author });
			});
		}

		[Fact]
		public async Task GivenAJobPostingAlreadyExists_WhenWeAttemptToCreateTheSameOne_ThenADuplicateUniqueIdExceptionIsThrown()
		{
			// Assert
			await Assert.ThrowsAsync<DuplicateUniqueIdException>(async () =>
			{
				// Act
				await jobPostingRepo.CreateManyAsync(new List<JobPosting> { jobPosting, jobPosting });
			});
		}

		[Fact]
		public async Task WhenWeCreateEmployeeWithAutoGeneratedUniqueIdProperty_ThenWeGetItBackWhenWeRetrieveIt()
		{
			// Act
			var createdEmployees = await employeeRepo.CreateManyAsync(new List<Employee> { employee });
			// Assert
			var retrievedEmployee = await GetExistingModelAsync(createdEmployees.First(), employeeRepo);
			Assert.Equal(employee.Salary, retrievedEmployee.Salary);
		}

		[Fact]
		public async Task WhenWeInsertMultipleEmployees_ThenWeGetBackEachEmployeeWithLocationIdSet()
		{
			// Act
			var createdEmployees = await employeeRepo.CreateManyAsync(employee, employee2, employee3);
			foreach (var createdEmployee in createdEmployees)
				// Assert
				Assert.NotEqual(-1L, createdEmployee.LocationId);
		}


		private async Task<TModel> GetExistingModelAsync<TModel>(TModel model, IAtomicRepository<TModel> repo)
			where TModel : class, new()
		{
			var retrievedModelOption = await repo.GetOneAsync(model);
			var retrievedModelExists = Assert.IsType<AtomicOption<TModel>.Exists>(retrievedModelOption);
			var retrievedModel = retrievedModelExists.Value;
			return retrievedModel;
		}

		public void Dispose()
		{
			Cleanup();
		}
		protected abstract void Cleanup();
	}
}
