using CalebBender.Atoms.DataAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AtomsIntegrationTests.Models
{
	public class Employee
	{
		[UniqueId]
		public Guid EmployeeId { get; set; }
		[UniqueId(AutoGenerated = true)]
		public long LocationId { get; set; } = -1L;
		public decimal Salary { get; set; }
	}
}
