using CalebBender.Atoms.DataAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AtomsIntegrationTests.Models
{
	public class ModelWithMultipleAutoGeneratedUniqueIds
	{
		[UniqueId(AutoGenerated = true)]
		public byte Id8 { get; set; }
		[UniqueId(AutoGenerated = true)]
		public short Id16 { get; set; }
		[UniqueId(AutoGenerated = true)]
		public int Id32 { get; set; }
		[UniqueId(AutoGenerated = true)]
		public long Id64 { get; set; }
	}
}
