using CalebBender.Atoms.DataAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AtomsIntegrationTests.Models
{
    public class TimeData
    {
        [UniqueId(AutoGenerated = true)]
        public int Id { get; set; }
        public TimeOnly Time { get; set; }
        public TimeSpan TimeSpan { get; set; }
    }
}
