using Atoms.DataAttributes;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace Atoms.Repositories.SqlServer.SqlGeneration
{
	internal static class InsertSqlGenerator<TModel>
		where TModel : class, new()
	{
		private static readonly string insertIntoText = GetInsertIntoText();

		internal static (string, IEnumerable<SqlParameter>, PropertyInfo?) GetInsertSqlTextForOne(TModel model)
		{
			List<SqlParameter> parameters = new List<SqlParameter>();
			PropertyInfo? identityModelProperty = null;
			foreach (var modelProperty in ModelMetadata<TModel>.PublicProperties)
			{
				if (PropertyIsAutoGeneratedUniqueId(modelProperty))
				{
					identityModelProperty = modelProperty; continue;
				}
				var databasePropertyName = PropertyMappingUtilities<TModel>.GetDbPropertyNameOfModelProperty(modelProperty);
				parameters.Add(new SqlParameter("@" + databasePropertyName, modelProperty.GetValue(model) ?? DBNull.Value));
			}
			var valuesText = $"VALUES ({string.Join(',', parameters.Select(parameter => parameter.ParameterName))});";
			var insertSqlText = insertIntoText + valuesText;
			if (identityModelProperty is not null)
			{
				insertSqlText += " SELECT SCOPE_IDENTITY();";
			}
			return (insertSqlText, parameters, identityModelProperty);
		}

		internal static object GetConvertedIdentityType(PropertyInfo identityModelProperty, object identityValue)
		{
			if (identityModelProperty.PropertyType == typeof(long))
				identityValue = Convert.ToInt64(identityValue);
			else if (identityModelProperty.PropertyType == typeof(int))
				identityValue = Convert.ToInt32(identityValue);
			else if (identityModelProperty.PropertyType == typeof(short))
				identityValue = Convert.ToInt16(identityValue);
			else if (identityModelProperty.PropertyType == typeof(byte))
				identityValue = Convert.ToByte(identityValue);
			return identityValue;
		}

		private static string GetInsertIntoText()
		{
			var insertIntoText = $"INSERT INTO [{ModelMetadata<TModel>.TableName}](";
			int i = 0;
			foreach (var modelProperty in ModelMetadata<TModel>.PublicProperties)
			{
				if (PropertyIsAutoGeneratedUniqueId(modelProperty)) continue;
				var databasePropertyName = PropertyMappingUtilities<TModel>.GetDbPropertyNameOfModelProperty(modelProperty);
				insertIntoText += $"[{databasePropertyName}]";
				if (++i < ModelMetadata<TModel>.PublicProperties.Count())
					insertIntoText += ", ";
			}
			insertIntoText += ") ";
			insertIntoText = insertIntoText.Replace(", )", ")");
			return insertIntoText;
		}

		private static bool PropertyIsAutoGeneratedUniqueId(PropertyInfo modelProperty)
		{
			return modelProperty.GetCustomAttribute<UniqueIdAttribute>() is UniqueIdAttribute uniqueIdAttribute && uniqueIdAttribute.AutoGenerated;
		}
	}
}
