using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Atoms.Exceptions
{
	public class AutoGeneratedUniqueIdMustBeAnIntegerTypeException : AtomsException
	{
		public AutoGeneratedUniqueIdMustBeAnIntegerTypeException(string? message = null) : base(message) { }
		public AutoGeneratedUniqueIdMustBeAnIntegerTypeException(string? message, Exception? innerException) : base(message, innerException)
		{
		}
	}
}
