using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CalebBender.Atoms.Exceptions
{
	/// <summary>
	/// This exception occurs when the database engine in use only allows for
	/// integer properties to be autogenerated (identity). This usually applies to
	/// SQL database engines.
	/// </summary>
	public class AutoGeneratedUniqueIdMustBeAnIntegerTypeException : AtomsException
	{
		public AutoGeneratedUniqueIdMustBeAnIntegerTypeException(string? message = null) : base(message) { }
		public AutoGeneratedUniqueIdMustBeAnIntegerTypeException(string? message, Exception? innerException) : base(message, innerException)
		{
		}
	}
}
