using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Atoms.Exceptions
{
	/// <summary>
	/// This exception occurs when a data model class contains more auto-generated
	/// unique ids than is supported by the database engine. For example, SQL Server
	/// only allows for one identity column per table, so a corresponding data class
	/// model should only have one auto-generated unique id property.
	/// </summary>
	public class TooManyAutoGeneratedUniqueIdsException : AtomsException
	{
		public TooManyAutoGeneratedUniqueIdsException(string? message = null) : base(message) { }
		public TooManyAutoGeneratedUniqueIdsException(string? message, Exception? innerException) : base(message, innerException)
		{
		}
	}
}
